{
 "title": "Digital Twin Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Qualitätskontrolle",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FactoryIO\")\r\n  |> range(start: -3h)\r\n  |> filter(fn: (r) => r._measurement == \"sensor\" and r.name == \"quality\")\r\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Aufteilung Produkte",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"FactoryIO\")\r\n  |> range(start: -3h)\r\n  |> filter(fn: (r) => r._measurement == \"product\")\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Gestartete Simulationen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FactoryIO\")\r\n  |> range(start: -3h, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"sensor\" and r.name == \"startsensor\")\r\n  |> count()\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Beendete Simulationen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FactoryIO\")\r\n  |> range(start: -3h, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"sensor\" and r.name==\"endsensor\")\r\n  |> count()\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Tank Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket:\"FactoryIO\")\r\n  |> range(start: -3h)\r\n  |> filter(fn: (r) => r._measurement == \"machine\" and r.name == \"tank\")"
    }
   ]
  }
 ]
}